# Maigo URL Shortener Configuration

# Database Configuration
database:
  host: localhost
  port: 5432
  name: maigo
  user: postgres
  password: password
  ssl_mode: disable
  max_conns: 10
  max_idle: 5

# HTTP Server Configuration
server:
  port: 8080
  host: 127.0.0.1
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

# SSH Server Configuration
ssh:
  port: 2222
  host: 127.0.0.1
  host_key_path: host_keys/ssh_host_rsa_key

# OAuth2 Configuration
oauth2:
  client_id: maigo_cli
  client_secret: dev_secret_change_in_production
  redirect_uri: urn:ietf:wg:oauth:2.0:oob

# JWT Configuration
jwt:
  secret: dev_jwt_secret_change_in_production
  expiration: 24h

# Application Configuration
app:
  base_domain: maigo.dev
  short_code_length: 6
  debug: true
  cors_enabled: true
  rate_limit:
    requests: 100
    window: 1h

# Logging Configuration
log:
  level: debug
  format: text
