app:
  name: "Maigo Test"
  environment: "test"
  port: 8080
  host: "0.0.0.0"
  log_level: "debug"
  rate_limit: 100
  cors_enabled: true
  short_code_length: 6
  base_url: "https://maigo.dev"

database:
  host: "localhost"
  port: 5432
  name: "maigo_test"
  user: "postgres"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

jwt:
  secret: "test-secret-key-for-testing-only"
  access_token_duration: "15m"
  refresh_token_duration: "24h"
  issuer: "maigo-test"

oauth:
  google:
    client_id: "test-client-id"
    client_secret: "test-client-secret"
    redirect_url: "http://localhost:8080/auth/google/callback"
  github:
    client_id: "test-client-id"
    client_secret: "test-client-secret"
    redirect_url: "http://localhost:8080/auth/github/callback"
