name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.23'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: maigo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Check formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not formatted. Please run 'make fmt'."
          gofmt -s -l .
          exit 1
        fi

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Check imports
      run: |
        if [ "$(goimports -l . | wc -l)" -gt 0 ]; then
          echo "Imports are not formatted. Please run 'make fmt'."
          goimports -l .
          exit 1
        fi

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout=5m

    - name: Run unit tests
      run: go test -v -race -short ./internal/...

    - name: Set up test environment
      env:
        PGPASSWORD: password
      run: |
        # Wait for PostgreSQL to be ready with timeout
        echo "Waiting for PostgreSQL to be ready..."
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Attempt $i: PostgreSQL not ready yet, waiting..."
          sleep 2
        done

        # Verify PostgreSQL is actually ready
        if ! pg_isready -h localhost -p 5432 -U postgres; then
          echo "PostgreSQL failed to start within timeout"
          exit 1
        fi

        # Build the maigo binary with proper PostgreSQL driver
        go build -o bin/maigo ./cmd/maigo

        # Run migrations using the built-in migrate command with environment variables
        DATABASE_URL="postgres://postgres:password@localhost:5432/maigo_test?sslmode=disable" ./bin/maigo migrate up

    - name: Run integration tests
      env:
        CONFIG_PATH: config/test.yaml
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: maigo_test
        DB_USER: postgres
        DB_PASSWORD: password
        DB_SSL_MODE: disable
      run: go test -v ./tests/...

    - name: Generate coverage report
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

        LDFLAGS="-ldflags -X main.Version=${VERSION} -X main.BuildTime=${BUILD_TIME} -X main.GitCommit=${GIT_COMMIT}"

        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="maigo-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
        else
          BINARY_NAME="maigo-${{ matrix.goos }}-${{ matrix.goarch }}"
        fi

        go build ${LDFLAGS} -o dist/${BINARY_NAME} ./cmd/maigo

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maigo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/

