
name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-binaries:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Release Binaries
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: '1.23'
          project_path: ./cmd/maigo
          binary_name: maigo
          ldflags: -s -w -X github.com/yukaii/maigo/cmd/maigo.version=${{ github.ref_name }} -X github.com/yukaii/maigo/cmd/maigo.commit=${{ github.sha }} -X github.com/yukaii/maigo/cmd/maigo.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: true
          compress_assets: auto
